### ISSUE TITLE
local dev plugin localization failed

### ISSUE THREAD

**Issue by hongxuchen** [tsakirist/telescope-lazy.nvim#5]
[lazy.nvim](https://github.com/folke/lazy.nvim) supports `dev` configuration, which allows specifying a directory to put local plugins inside; for the specific plugin, lazy.nvim will look up in the specified directory for such a plugin, if the plugin is configured with `dev = true`.

When I set a local plugin, telescope-lazy.nvim successfully displays the plugin name in telescope's picker list, but it seems to fail to find the correct location of the plugin. For example, when I press `<CR>` it emits an error message `Could not perform action. Readme file doesn't exist.`; `<C-F>` and others don't work either.

**Comment by tsakirist** [comment]
Thanks for the issue.

I've just added support for `dev` mode plugins in 1b98d08.
