### ISSUE TITLE
Feature Request: change working directory action

### ISSUE THREAD

**Issue by kevintraver** [tsakirist/telescope-lazy.nvim#7]
A telescope action to change the working directory to the selected entry.

Probably something similar to this:

https://github.com/nvim-telescope/telescope.nvim/wiki/Configuration-Recipes#change-directory

or this:

https://github.com/ahmedkhalf/project.nvim/blob/8c6bad7d22eef1b71144b401c9f74ed01526a4fb/lua/telescope/_extensions/projects.lua#L62-L76

Happy to help with a PR

**Comment by tsakirist** [comment]
Hi Kevin, thanks for the feature request.

I think it would also be useful to add a key mapping for users to be able to return back to the previous directory after having performed the "cd" operation, something for consideration. 

If I'll find some spare time I'll try to look into it.

**Comment by tsakirist** [comment]
Just pushed 0d6705f that adds this functionality.
Feel free to test it out!
